#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../testdata_tools/gen.sh

use_solution sol.py

compile random_generator.py

sample 01
sample 02
sample 03

for i in {01..40}; do
tc random-$i random_generator -10000 10000 -10000 10000
done;
